@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-lg-9">
            <div class="iq-card">
                <div class="iq-card-header d-flex justify-content-between">
                    <div class="iq-header-title">
                        <h4 class="card-title"><strong>Add User:</strong></h4>
                    </div>
                </div>
                <div class="iq-card-body">
                    {!! Form::open(array('route' => 'users.store','method'=>'POST')) !!}
                        <div class=" row align-items-center">
                            <div class="form-group col-sm-6">
                                <label for="fname">First Name:</label>
                                {!! Form::text('fName', null, array('placeholder' => 'Enter first name', 'class' => "form-control", 'id' => 'fName')) !!}
                                @error('fName')
                                    <script>$('#fName').css("border", "1px solid red");</script>
                                    <div class="alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="lname">Last Name:</label>
                                {!! Form::text('lName', null, array('placeholder' => 'Enter last name', 'class' => "form-control", 'id' => 'lName')) !!}
                                @error('lName')
                                    <script>$('#lName').css("border", "1px solid red");</script>
                                    <div class="alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="username">Username:</label>
                                <a href="#" data-toggle="tooltip" data-placement="right" title="Password will be autogenerated from username. Example: {username}@123" style="cursor: pointer; left-padding:0">
                                    <i class="ri-information-fill"></i>
                                </a>
                                {!! Form::text('username', null, array('placeholder' => 'Enter username', 'class' => "form-control", 'id' => 'username')) !!}
                                @error('username')
                                    <script>$('#username').css("border", "1px solid red");</script>
                                    <div class="alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="email">Gender:</label>
                                {!! Form::select('gender', ['M' => 'Male', 'F' => 'Female'], null, ['placeholder' => 'Please select...', 'class' => 'form-control', 'id' => 'gender']) !!}
                                @error('gender')
                                    <script>$('#gender').css("border", "1px solid red");</script>
                                    <div class="alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="email">Email:</label>
                                {!! Form::text('email', null, array('placeholder' => 'Enter email', 'class' => "form-control", 'id' => 'email')) !!}
                                @error('email')
                                    <script>$('#email').css("border", "1px solid red");</script>
                                    <div class="alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="phone_number">Phone Number:</label>
                                {!! Form::text('phone_number', null, array('placeholder' => 'Enter phone number', 'class' => "form-control", 'id' => 'phoneNum')) !!}
                                @error('phone_number')
                                    <script>$('#phoneNum').css("border", "1px solid red");</script>
                                    <div class="alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="editTag">Role:</label>
                                {!! Form::select('role', $roles->pluck('name', 'id'), null, ['placeholder' => 'Please select...', 'class' => 'form-control', 'id' => 'role']) !!}
                                @error('role')
                                    <script>$('#role').css("border", "1px solid red");</script>
                                    <div class="alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="editTag">Beacon:</label>
                                {!! Form::select('beacon_id', $tagsNull, null, ['placeholder' => 'Please select...', 'class' => 'form-control', 'id' => 'tag']) !!}
                                @error('beacon_id')
                                    <script>$('#tag').css("border", "1px solid red");</script>
                                    <div class="alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="text-center mt-5">
                            <button type="submit" class="btn btn-primary">Save User</button>
                            @php(session(['user' => 'page']))
                            <a href="{{ route('settings.index') }}" class="btn btn-secondary">Cancel</a>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')

@endsection